### PR TITLE
Remove int tests from GH Actions

### PR DESCRIPTION
**Pull request by ives1227**
Removes the integration tests from GH Actions.

### CODE REVIEW

**Review by awoods — COMMENTED** [review]
Are we removing the integration tests because they will be run in a different context?

**Comment by ives1227** [comment]
> Are we removing the integration tests because they will be run in a different context?

@awoods yes - I put some info in Slack:
"We are removing the integration tests from GH Actions because Jenkins will run these.  For integration tests to run in GH Actions, we will need various URLs open to GH (eg DIMS healthcheck endpoint).  Since Jenkins will run the int tests from the server that we need these URLs open to, it doesn't make sense to open them to GH just to get the actions to work.  We will leave the unit tests in the GH Actions."
However, this does seem like it will affect the coverage so we will need to discuss further whether the coverage calculation can be done in Jenkins as well or we will have to open the URLs to GH.

**Comment by awoods** [comment]
We will also want to change the text on the badge: https://github.com/harvard-lts/etd_alma_monitor_service#readme
That appears to be set here: https://github.com/harvard-lts/etd_alma_monitor_service/blob/main/.github/workflows/pytest.yml#LL1C1-L1C1

**Comment by awoods** [comment]
@ives1227 : or we decide on a unit test coverage threshold.

**Comment by ives1227** [comment]
@awoods yes - we will have to discuss further.

**Pull request closed without merging**
